# Global Configuration
global:
   scrape_interval: 15s 
   evaluation_interval: 15s
#Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs: 
        - targets: 
          -  'localhost:9093'

#Scrape configuration
scrape_configs:
 - job_name: 'prometheus'
   scrape_interval: 5s
   static_configs:
     - targets: ['localhost:9090']
 - job_name: 'node_exporter'
   static_configs:
     - targets: ['localhost:9100']
 - job_name: 'my_app'
   static_configs: 
     - targets: [ip:8080]